# URL pointing to a reference fasta file
fa: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_31/GRCh37_mapping/GRCh37.primary_assembly.genome.fa.gz'

# URL pointing to a annotation gtf file
gtf: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_31/GRCh37_mapping/gencode.v31lift37.annotation.gtf.gz'

# Removing duplicate entries in par_y regions for genode human releases. Can be set as false for other organisms
filt_parY: TRUE

# Star overhang length for reference index creation. Usually a value of 100 should do for reads of 75-150bp
# But you may want a shorted value for reads <50bp. In this case you can set it to 100,50 to generate two indices.
star_overhang_lengths: "100"
