# Maximum number of threads to use
threads: 1

# URL pointing to a reference fasta file
fa: 'https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/GRCm38.primary_assembly.genome.fa.gz'

# URL pointing to a annotation gtf file
gtf: 'https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.primary_assembly.annotation.gtf.gz'

# URL pointing to transcript seqeuences
transcripts_fa: 'https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.transcripts.fa.gz'

# URL to get blacklist bed files
blacklist_bed_url: 'https://raw.githubusercontent.com/Boyle-Lab/Blacklist/master/lists/mm10-blacklist.v2.bed.gz'

# Removing duplicate entries in par_y regions for genode human releases. Can be set as false for other organisms
filt_parY: FALSE

# Flags to create/skip particular indices
kallisto_idx: FALSE
star_idx: FALSE
salmon_idx: FALSE
bowtie_idx: FALSE
bowtie2_idx: FALSE

# Star overhang length for reference index creation. Usually a value of 100 should do for reads of 75-150bp
# But you may want a shorted value for reads <50bp. In this case you can set it to 100,50 to generate two indices.
star_overhang_lengths: "100"

